add test for list rule with service group id
IBM/platform-services-java-sdk pull request #157
Opened 2022-10-12 22:11 UTC by cam-d12

Signed-off-by: Cameron Davis <cjdavis@ibm.com>

## PR summary

This PR adds CBR support for the new service_group_id parameter in rules.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

No current behavior should be modified. Adds the further control to be able to apply rules to service groups

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information

2022-10-12 22:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/IBM/platform-services-java-sdk?pullRequest=157) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/IBM/platform-services-java-sdk?pullRequest=157) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/IBM/platform-services-java-sdk?pullRequest=157) it.</sub>

2022-10-13 13:29 UTC, soohoowoohoo requested changes

2022-10-13 13:29 UTC, soohoowoohoo commented on modules/context-based-restrictions/src/test/java/com/ibm/cloud/platform_services/context_based_restrictions/v1/ContextBasedRestrictionsIT.java
> +            assertEquals(ruleListResult.getTotalCount(), 1)
can we assert the rule ID from line 674 is the rule that is returned?

2022-10-14 13:55 UTC, soohoowoohoo reviewed
LGTM

2022-10-14 22:03 UTC, padamstx approved these changes
LGTM

2022-10-14 22:08 UTC, merged

2022-10-14 22:20 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 0.26.1 :tada:

The release is available on [GitHub release](https://github.com/IBM/platform-services-java-sdk/releases/tag/0.26.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: